export { default as dataRouter } from './data'
export { default as landingRouter } from './landing'
export { default as loginRouter } from './login'
export { default as logoutRouter } from './logout'
export { default as oauthRouter } from './oauth'
export { default as oidcRouter } from './oidc'
export { default as profileRouter } from './profile'
export { default as registerRouter } from './register'
